const { describe, it } = require('node:test');
const assert = require('node:assert');
const path = require('path');
const { LockFileParser } = require('../dist/parsers/LockFileParser');

describe('LockFileParser', () => {
  const parser = new LockFileParser();
  const fixturesDir = path.join(__dirname, 'fixtures');

  it('should parse package-lock.json file', () => {
    const filePath = path.join(fixturesDir, 'test-package-lock.json');
    const lockFile = parser.parseFile(filePath);

    assert.strictEqual(lockFile.lockfileVersion, 2);
    assert.strictEqual(lockFile.name, 'test-package');
    assert.strictEqual(lockFile.version, '1.0.0');
  });

  it('should parse package-lock.json from string', () => {
    const content = JSON.stringify({
      lockfileVersion: 2,
      name: 'test',
      version: '1.0.0',
      dependencies: {
        'express': {
          version: '4.18.2'
        }
      }
    });

    const lockFile = parser.parsePackageLock(content);
    assert.strictEqual(lockFile.lockfileVersion, 2);
    assert.ok(lockFile.dependencies);
    assert.strictEqual(lockFile.dependencies['express'].version, '4.18.2');
  });

  it('should get resolved version from package-lock.json', () => {
    const filePath = path.join(fixturesDir, 'test-package-lock.json');
    const lockFile = parser.parseFile(filePath);

    const expressVersion = parser.getResolvedVersion(lockFile, 'express');
    assert.strictEqual(expressVersion, '4.18.2');

    const lodashVersion = parser.getResolvedVersion(lockFile, 'lodash');
    assert.strictEqual(lodashVersion, '4.17.21');
  });

  it('should get all locked dependencies', () => {
    const filePath = path.join(fixturesDir, 'test-package-lock.json');
    const lockFile = parser.parseFile(filePath);

    const lockedDeps = parser.getAllLockedDependencies(lockFile);
    assert.ok(lockedDeps.has('express'));
    assert.ok(lockedDeps.has('lodash'));
    assert.ok(lockedDeps.has('body-parser'));
    
    assert.strictEqual(lockedDeps.get('express'), '4.18.2');
    assert.strictEqual(lockedDeps.get('lodash'), '4.17.21');
  });

  it('should return undefined for non-existent package', () => {
    const filePath = path.join(fixturesDir, 'test-package-lock.json');
    const lockFile = parser.parseFile(filePath);

    const version = parser.getResolvedVersion(lockFile, 'non-existent');
    assert.strictEqual(version, undefined);
  });

  it('should parse yarn.lock format', () => {
    const yarnLockContent = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
  integrity sha512-abc123

lodash@~4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-def456
`;

    const lockFile = parser.parseYarnLock(yarnLockContent);
    assert.strictEqual(lockFile.type, 'yarn');
    assert.ok(lockFile.entries);
    
    // Check that entries were parsed
    const keys = Object.keys(lockFile.entries);
    assert.ok(keys.length > 0);
  });
});
